[tool.poetry]
name = "fastapi-base"
version = "0.1.0"
description = ""
authors = ["Valera <v.medovkin1664@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
